kind: pipeline
name: default
steps:
- name: build
  image: node:11
  commands:
  - yarn install
  - yarn build
  environment:
    ACCESS_TOKEN:
      from_secret: ACCESS_TOKEN
    CONTENTFUL_HOST:
      from_secret: CONTENTFUL_HOST
- name: publish
  image: plugins/docker
  settings:
    username: nologin
    password:
      from_secret: deploy_token
    registry: rg.fr-par.scw.cloud/ipcloud
    repo: rg.fr-par.scw.cloud/ipcloud/ivopatty-nl
