kind: pipeline
name: default
steps:
- name: test
  image: node:11
  commands:
  - yarn install
  - yarn build
  environment:
    ACCESS_TOKEN:
      from_secret: ACCESS_TOKEN
    CONTENTFUL_HOST:
      from_secret: CONTENTFUL_HOST
